google.maps.__gjsload__('geometry', function(_){var Ama=function(a,b){return Math.abs(_.vl(b-a,-180,180))},Bma=function(a,b,c,d,e){if(!d){c=Ama(a.lng(),c)/Ama(a.lng(),b.lng());if(!e)return e=Math.sin(_.Bk(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Bk(b.lat())),_.Ck(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.Sn(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Bk(a.lat());a=_.Bk(a.lng());d=_.Bk(b.lat());b=_.Bk(b.lng());c=_.Bk(c);return _.vl(_.Ck(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},Cma=function(a,b){a=new _.sm(a,!1);b=new _.sm(b,!1);return a.equals(b)},Dma=function(a,b,c){a=_.ym(a);c=c||1E-9;const d=_.vl(a.lng(),-180,180),e=b instanceof _.Wv,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(let r=0,u=g.getLength();r<u;++r){const w=g.getAt(r),x=w.getLength(),y=e?x:x-1;for(let D=0;D<y;++D){var h=w.getAt(D);const I=w.getAt((D+
1)%x);if(Cma(h,a)||Cma(I,a))return!0;var l=_.vl(h.lng(),-180,180),n=_.vl(I.lng(),-180,180);const L=Math.max(l,n),K=Math.min(l,n);if(l=Math.abs(_.vl(l-n,-180,180))<=1E-9&&(Math.abs(_.vl(l-d,-180,180))<=c||Math.abs(_.vl(n-d,-180,180))<=c)){l=a.lat();n=Math.min(h.lat(),I.lat())-c;var p=Math.max(h.lat(),I.lat())+c;l=l>=n&&l<=p}if(l)return!0;if(L-K>180?d+c>=L||d-c<=K:d+c>=K&&d-c<=L)if(h=Bma(h,I,d,f,b),Math.abs(h-a.lat())<c)return!0}}return!1},Ema=function(a,b){const c=_.um(a);a=_.vm(a);const d=_.um(b);
b=_.vm(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},Fma=function(a,b,c){a=_.ym(a);b=_.ym(b);c=c||6378137;return Ema(a,b)*c},Ima=function(a,b){b=b||6378137;a instanceof _.Mo&&(a=a.getArray());a=(0,_.Zt)(a);if(a.length===0)return 0;const c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);Gma(a[a.length-1],f);for(let w=0;w<a.length;++w)Gma(a[w],d),NE(f,d,c),Hma(c,e,e),[f[0],f[1],f[2]]=d;const [g,h,l]=f,[n,p,r,u]=e;return 2*Math.atan2(g*
p+h*r+l*u,n)*(b*b)},Jma=function(a,b){if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=a*90;if(c===30||c===-30){c=Math.sign(c)*.5;var d=Math.sqrt(.75)}else c===45||c===-45?(c=Math.sign(c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN},Gma=function(a,b){const c=Array(2);Jma(a.lat(),c);const [d,e]=c;Jma(a.lng(),c);const [f,g]=c;
b[0]=e*g;b[1]=e*f;b[2]=d},Hma=function(a,b,c){const d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f},NE=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2];const g=a[0]+b[0],h=a[1]+b[1],l=a[2]+b[2];var n=g*g+h*h+l*l,p=e*l-f*h;f=f*g-d*l;d=d*h-e*g;e=n*n+p*p+f*f+d*d;if(e!==0)b=Math.sqrt(e),c[0]=n/b,c[1]=p/b,c[2]=f/b,c[3]=d/b;else{a:for(n=[a[0]-b[0],a[1]-
b[1],a[2]-b[2]],p=0;p<3;++p)if(n[p]!==0){if(n[p]<0){n=[-n[0],-n[1],-n[2]];break a}break}p=0;for(f=1;f<n.length;++f)Math.abs(n[f])<Math.abs(n[p])&&(p=f);f=[0,0,0];f[p]=1;n=[n[1]*f[2]-n[2]*f[1],n[2]*f[0]-n[0]*f[2],n[0]*f[1]-n[1]*f[0]];p=Math.hypot(...n);n=[n[0]/p,n[1]/p,n[2]/p];p=Array(4);NE(a,n,p);a=Array(4);NE(n,b,a);Hma(a,p,c)}},OE=class{};OE.isLocationOnEdge=Dma;
OE.containsLocation=function(a,b){a=_.ym(a);const c=_.vl(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs");var f=b.get("map");f=!d&&f?f.getProjection():null;let g=!1;for(let l=0,n=e.getLength();l<n;++l){const p=e.getAt(l);for(let r=0,u=p.getLength();r<u;++r){const w=p.getAt(r),x=p.getAt((r+1)%u);var h=_.vl(w.lng(),-180,180);const y=_.vl(x.lng(),-180,180),D=Math.max(h,y);h=Math.min(h,y);(D-h>180?c>=D||c<h:c<D&&c>=h)&&Bma(w,x,c,d,f)<a.lat()&&(g=!g)}}return g||Dma(a,b)};var PE=class{};PE.computeSignedArea=Ima;
PE.computeArea=function(a,b){if(!(a instanceof _.Mo||Array.isArray(a)||a instanceof _.zn||a instanceof _.To))try{a=_.yn(a)}catch(c){try{a=new _.To((0,_.Ds)(a))}catch(d){throw _.Yl("Invalid path passed to computeArea(): "+JSON.stringify(a));}}b=b||6378137;if(a instanceof _.To){if(a.getRadius()===void 0)throw _.Yl("Invalid path passed to computeArea(): Circle is missing radius.");if(a.getRadius()<0)throw _.Yl("Invalid path passed to computeArea(): Circle must have non-negative radius.");if(b<0)throw _.Yl("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");
if(a.getRadius()>Math.PI*b)throw _.Yl("Invalid path passed to computeArea(): Circle must not cover more than 100% of the sphere.");return 2*Math.PI*b**2*(1-Math.cos(a.getRadius()/b))}if(a instanceof _.zn){if(b<0)throw _.Yl("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");if(a.ni.lo>a.ni.hi)throw _.Yl("Invalid path passed to computeArea(): the southern LatLng of a LatLngBounds cannot be more north than the northern LatLng.");let c=2*Math.PI*b**2*(1-Math.cos((a.ni.lo-
90)*Math.PI/180));c-=2*Math.PI*b**2*(1-Math.cos((a.ni.hi-90)*Math.PI/180));return c*Math.abs(a.Lh.hi-a.Lh.lo)/360}return Math.abs(Ima(a,b))};PE.computeLength=function(a,b){b=b||6378137;let c=0;a instanceof _.Mo&&(a=a.getArray());for(let d=0,e=a.length-1;d<e;++d)c+=Fma(a[d],a[d+1],b);return c};PE.computeDistanceBetween=Fma;
PE.interpolate=function(a,b,c){a=_.ym(a);b=_.ym(b);const d=_.um(a);var e=_.vm(a);const f=_.um(b),g=_.vm(b),h=Math.cos(d),l=Math.cos(f);b=Ema(a,b);const n=Math.sin(b);if(n<1E-6)return new _.sm(a.lat(),a.lng());a=Math.sin((1-c)*b)/n;c=Math.sin(c*b)/n;b=a*h*Math.cos(e)+c*l*Math.cos(g);e=a*h*Math.sin(e)+c*l*Math.sin(g);return new _.sm(_.Ck(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Ck(Math.atan2(e,b)))};
PE.computeOffsetOrigin=function(a,b,c,d){a=_.ym(a);c=_.Bk(c);b/=d||6378137;d=Math.cos(b);const e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.um(a));const f=e*e*d*d+d*d*d*d-d*d*c*c;if(f<0)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;const h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.vm(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.sm(_.Ck(g),_.Ck(a))};
PE.computeOffset=function(a,b,c,d){a=_.ym(a);b/=d||6378137;c=_.Bk(c);var e=_.um(a);a=_.vm(a);d=Math.cos(b);b=Math.sin(b);const f=Math.sin(e);e=Math.cos(e);const g=d*f+b*e*Math.cos(c);return new _.sm(_.Ck(Math.asin(g)),_.Ck(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};PE.computeHeading=function(a,b){a=_.ym(a);b=_.ym(b);const c=_.um(a),d=_.vm(a);a=_.um(b);b=_.vm(b)-d;return _.vl(_.Ck(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)};var Kma={encoding:_.sw,spherical:PE,poly:OE};_.oa.google.maps.geometry=Kma;_.Yk("geometry",Kma);});
